---
title: "Spatial Analysis A1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(ggspatial)
library(sf)
library(ggthemes)
```
```{r}
parks <- st_read("parks.kml")
schools <- st_read("schools.kml")
```



```{r}

ggplot() +
  
  annotation_map_tile(zoomin = 0, progress = "none", type = "hotstyle") +

  geom_sf(data = parks, color = NA, 
          aes(fill = "Public Space")) +

  geom_sf(data = schools, size = 1, shape = 20, alpha = 0.25, aes(color = "Schools")) +

  labs(caption = "School Access to Public Space in NYC") +
  
  scale_fill_manual(values = "forestgreen", name = "") +
  
  scale_color_manual(values = c("red"), name = "")

```

```{r}

ggplot() +

  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenwatercolor") +

  geom_sf(data = parks, color = "#dc7dfd", alpha = 0.85) +

  geom_sf(data = schools, color = "#fbfd7d", size = 1, shape = 11, alpha = 0.8) +

  labs(caption = "A Bad Map That Resembles Bubblegum")

```